### ISSUE TITLE
Errors trying to run with sample file

### ISSUE THREAD

**Issue by jstanis731** [hamzaehsan97/CSS-optomizer#4]
Errors being reported:
`Traceback (most recent call last):
  File "/Users/jonathanstanis/github/CSS-optomizer-master/main.py", line 278, in <module>
    CSSList = rulesNamesLabelsTuple(stylesheet)
  File "/Users/jonathanstanis/github/CSS-optomizer-master/main.py", line 171, in rulesNamesLabelsTuple
    CSSDict["rules"]=seperatedRules(stylesheet, i)
  File "/Users/jonathanstanis/github/CSS-optomizer-master/main.py", line 142, in seperatedRules
    rulesCommaSeperated = seperateByComma(stylesheet, i)
  File "/Users/jonathanstanis/github/CSS-optomizer-master/main.py", line 43, in seperateByComma
    rule = stylesheet.rules[i].selector.as_css()
AttributeError: 'ImportRule' object has no attribute 'selector'`

**Comment by jstanis731** [comment]
[styling.CSS.zip](https://github.com/hamzaehsan97/CSS-optomizer/files/6416438/styling.CSS.zip)

**Comment by hamzaehsan97** [comment]
This issue is in relation to an environment misconfiguration. To avoid this issue we can use Anaconda to manage python environments. Here is a link to Anaconda's website https://www.anaconda.com/
